require_relative 'src/menu'
require_relative 'src/core_job'
require_relative 'src/file_list'
require_relative 'src/init_job'
require_relative 'src/java_program'
require_relative 'src/job_node'
require_relative 'src/labeled_job_node'
require_relative 'src/matlab_script'
require_relative 'src/ruby_script.rb'
require_relative 'src/sc_job.rb'
require_relative 'src/script_arg.rb'
require_relative 'src/selection_state.rb'
require_relative 'src/ker_lin_job.rb'

Menu.new
