clc;
%clear all;
close all;

DATASET = 'car2';
COMPUTE_EIGS = false;
USE_EIGS = true;
STEPSIZE_DATA = 8;
LAMBDA = 0.1% 7000%0.1;
USE_T = false;
SHOULD_LOAD_W = true;
PERFORM_AUTO_RESCALE = false;
USE_CLUSER_EW_COUNT = false;

THRESH = 0.000;
CLUSTER_CENTER_COUNT = 8;

USE_W_VEC = true;
USE_CLUSTERING_CUE = false;

SELECT_AFFINITY_IDX = false
SELECTED_ENTITY_IDX = 301;
frame_idx = 3;

%%
if exist('W','var') == 0
    disp('setting initial values...')
    W = 1; U = 1; S=1; WW = 1;
end
[W, U, S, WW] = run_clustering(DATASET, STEPSIZE_DATA, CLUSTER_CENTER_COUNT, THRESH, COMPUTE_EIGS, USE_EIGS, USE_W_VEC, USE_CLUSTERING_CUE, W, U, S, SELECTED_ENTITY_IDX, USE_T, frame_idx, WW, SHOULD_LOAD_W, PERFORM_AUTO_RESCALE, LAMBDA, USE_CLUSER_EW_COUNT, SELECT_AFFINITY_IDX);


